### ISSUE TITLE
Updated to Hentai@Home 1.6.2

### ISSUE THREAD

**Issue by huasheng666** [frosty5689/docker-hath#3]
Latest version released,hope can follow the update if possible.Thanks.
https://hub.docker.com/r/frosty5689/hath/
https://forums.e-hentai.org/index.php?showtopic=234458

**Comment by frosty5689** [comment]
Updated to H@H 1.6.2, had to update to GitHub Workflows as Docker Hub no longer allows free accounts to use their build server.

The arm64 image is untested, if anyone uses an arm64 server to run H@H, please let me know if something is not working.
